--
-- Copyright 2026 SkillTree
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     https://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- *********************************************************************
-- Initial Schema to support 4.7.0 Release
--   Prior to 4.7.0, Liquibase was utilized.
--   Users upgrading to 4.7.0+ from a version earlier than 4.6.0 must first upgrade to 4.6.0 before upgrading to 4.7.0.
-- *********************************************************************
-- Generated from: src/main/resources/db/changelog/db.changelog-master.xml
-- Command: mvn liquibase:updateSQL -Dliquibase.url=offline:postgresql
-- *********************************************************************

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::1::skills team
CREATE TABLE skills_db_locks (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, lock VARCHAR(255) NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT skills_db_locks_pkey PRIMARY KEY (id));

CREATE UNIQUE INDEX index_skills_db_locks_lock ON skills_db_locks(lock);

INSERT INTO skills_db_locks (lock) VALUES ('projects_lock');

INSERT INTO skills_db_locks (lock) VALUES ('global_badges_lock');

INSERT INTO skills_db_locks (lock) VALUES ('global_settings_lock');

CREATE TABLE project_definition (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, client_secret VARCHAR(255) NOT NULL, total_points INTEGER DEFAULT 0 NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT project_definition_pkey PRIMARY KEY (id));

CREATE UNIQUE INDEX index_project_definition_project_id ON project_definition(project_id);

CREATE UNIQUE INDEX index_project_definition_name ON project_definition(name);

CREATE TABLE custom_icons (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_id VARCHAR(255), proj_ref_id INTEGER, filename VARCHAR(255) NOT NULL, content_type VARCHAR(255) NOT NULL, data_uri TEXT NOT NULL, width INTEGER NOT NULL, height INTEGER NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT custom_icons_pkey PRIMARY KEY (id));

CREATE INDEX index_custom_icons_project_id ON custom_icons(project_id);

CREATE INDEX index_custom_icons_filename ON custom_icons(filename);

CREATE UNIQUE INDEX index_custom_icons_project_id_filename ON custom_icons(project_id, filename);

ALTER TABLE custom_icons ADD CONSTRAINT fk_custom_icons_project_definition_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE custom_icons ADD CONSTRAINT fk_custom_icons_proj_ref_id_project_definition_id FOREIGN KEY (proj_ref_id) REFERENCES project_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE skill_definition (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_id VARCHAR(255), skill_id VARCHAR(255) NOT NULL, proj_ref_id INTEGER, name VARCHAR(255) NOT NULL, point_increment INTEGER DEFAULT 100 NOT NULL, point_increment_interval INTEGER DEFAULT 8 NOT NULL, increment_interval_max_occurrences INTEGER DEFAULT 1 NOT NULL, total_points INTEGER DEFAULT 200 NOT NULL, description TEXT, help_url TEXT, display_order INTEGER NOT NULL, type VARCHAR(255) NOT NULL, custom_icon_ref_id INTEGER, icon_class VARCHAR(255), start_date TIMESTAMP WITHOUT TIME ZONE, end_date TIMESTAMP WITHOUT TIME ZONE, version INTEGER DEFAULT 0 NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT skill_definition_pkey PRIMARY KEY (id));

CREATE INDEX index_skill_definition_project_id ON skill_definition(project_id);

CREATE INDEX index_skill_definition_skill_id ON skill_definition(skill_id);

CREATE INDEX index_skill_definition_name ON skill_definition(name);

CREATE INDEX index_skill_definition_type ON skill_definition(type);

CREATE INDEX index_skill_definition_version ON skill_definition(version);

CREATE UNIQUE INDEX index_skill_definition_project_id_skill_id ON skill_definition(project_id, skill_id);

CREATE UNIQUE INDEX index_skill_definition_project_id_skill_id_type ON skill_definition(project_id, skill_id, type);

CREATE UNIQUE INDEX index_skill_definition_project_id_name_type ON skill_definition(project_id, name, type);

ALTER TABLE skill_definition ADD CONSTRAINT fk_skill_definition_project_definition_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE skill_definition ADD CONSTRAINT fk_skill_definition_proj_ref_id_project_definition_id FOREIGN KEY (proj_ref_id) REFERENCES project_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE skill_definition ADD CONSTRAINT fk_skill_definition_custom_icon_id_custom_icons_id FOREIGN KEY (custom_icon_ref_id) REFERENCES custom_icons (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE skill_relationship_definition (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, parent_ref_id INTEGER NOT NULL, child_ref_id INTEGER NOT NULL, type VARCHAR(255) NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT skill_relationship_definition_pkey PRIMARY KEY (id));

CREATE INDEX index_skill_relationship_definition_parent ON skill_relationship_definition(parent_ref_id);

CREATE INDEX index_skill_relationship_definition_child ON skill_relationship_definition(child_ref_id);

CREATE INDEX index_skill_relationship_definition_type ON skill_relationship_definition(type);

CREATE INDEX index_skill_relationship_definition_parent_type ON skill_relationship_definition(parent_ref_id, type);

CREATE INDEX index_skill_relationship_definition_child_type ON skill_relationship_definition(child_ref_id, type);

CREATE UNIQUE INDEX index_skill_relationship_definition_parent_child_type ON skill_relationship_definition(parent_ref_id, child_ref_id, type);

ALTER TABLE skill_relationship_definition ADD CONSTRAINT fk_skill_rel_parent_id_skill_def_id FOREIGN KEY (parent_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE skill_relationship_definition ADD CONSTRAINT fk_skill_rel_child_ref_id_skill_def_id FOREIGN KEY (child_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE skill_share_definition (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, skill_ref_id INTEGER NOT NULL, shared_to_project_ref_id INTEGER, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT skill_share_definition_pkey PRIMARY KEY (id));

CREATE UNIQUE INDEX index_skill_share_definition_skill_id_shared_to_project_id ON skill_share_definition(skill_ref_id, shared_to_project_ref_id);

ALTER TABLE skill_share_definition ADD CONSTRAINT fk_skill_id_skill_share_definition_skill_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE skill_share_definition ADD CONSTRAINT fk_skill_id_skill_share_definition_shared_to_project_id FOREIGN KEY (shared_to_project_ref_id) REFERENCES project_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE level_definition (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_ref_id INTEGER, skill_ref_id INTEGER, level INTEGER NOT NULL, percent INTEGER, points_from INTEGER, points_to INTEGER, custom_icon_ref_id INTEGER, icon_class VARCHAR(255), logical_name VARCHAR(255), created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT level_definition_pkey PRIMARY KEY (id));

CREATE INDEX index_level_definition_project_id ON level_definition(project_ref_id);

CREATE INDEX index_level_definition_skill_id ON level_definition(skill_ref_id);

ALTER TABLE level_definition ADD CONSTRAINT fk_skill_definition_skill_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE level_definition ADD CONSTRAINT fk_skill_definition_project_id FOREIGN KEY (project_ref_id) REFERENCES project_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE user_attrs (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, first_name VARCHAR(255), last_name VARCHAR(255), dn VARCHAR(255), email VARCHAR(255), nickname VARCHAR(255), user_id_for_display VARCHAR(255) NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT user_attrs_pkey PRIMARY KEY (id));

CREATE UNIQUE INDEX index_users_attrs_user_id ON user_attrs(user_id);

CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, password VARCHAR(255), created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT users_pkey PRIMARY KEY (id));

CREATE UNIQUE INDEX index_users_user_id ON users(user_id);

ALTER TABLE users ADD CONSTRAINT fk_users_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE user_roles (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_ref_id INTEGER NOT NULL, user_id VARCHAR(255) NOT NULL, role_name VARCHAR(255) NOT NULL, project_id VARCHAR(255), created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT user_roles_pkey PRIMARY KEY (id));

CREATE INDEX index_user_roles_user_id ON user_roles(user_id);

CREATE UNIQUE INDEX index_user_roles_user_id_role_name_project_id ON user_roles(user_id, role_name, project_id);

ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_user_ref_id FOREIGN KEY (user_ref_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE user_performed_skill (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, skill_ref_id INTEGER NOT NULL, skill_id VARCHAR(255) NOT NULL, project_id VARCHAR(255) NOT NULL, performed_on TIMESTAMP WITHOUT TIME ZONE NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT user_performed_skill_pkey PRIMARY KEY (id));

CREATE INDEX index_user_performed_skill_user_id ON user_performed_skill(user_id);

CREATE INDEX index_user_performed_skill_project_id ON user_performed_skill(project_id);

CREATE INDEX index_user_performed_skill_skill_id ON user_performed_skill(skill_id);

CREATE INDEX index_user_performed_skill_skill_ref_id ON user_performed_skill(skill_ref_id);

CREATE INDEX index_user_performed_skill_performed_on ON user_performed_skill(performed_on);

ALTER TABLE user_performed_skill ADD CONSTRAINT fk_user_performed_skill_skill_ref_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_performed_skill ADD CONSTRAINT fk_user_performed_skill_proj_id_skill_id FOREIGN KEY (project_id, skill_id) REFERENCES skill_definition (project_id, skill_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_performed_skill ADD CONSTRAINT fk_user_performed_skill_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE user_points (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, project_id VARCHAR(255) NOT NULL, skill_ref_id INTEGER, skill_id VARCHAR(255), points INTEGER NOT NULL, day date, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT user_points_pkey PRIMARY KEY (id));

CREATE INDEX index_user_points_project_id ON user_points(project_id);

CREATE INDEX index_user_points_skill_ref_id ON user_points(skill_ref_id);

CREATE INDEX index_user_points_skill_id ON user_points(skill_id);

CREATE INDEX index_user_points_user_id ON user_points(user_id);

CREATE INDEX index_user_points_day ON user_points(day);

CREATE INDEX index_user_points_points ON user_points(points);

ALTER TABLE user_points ADD CONSTRAINT fk_user_points_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_points ADD CONSTRAINT fk_user_points_skill_ref_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_points ADD CONSTRAINT fk_user_points_proj_id_skill_id FOREIGN KEY (project_id, skill_id) REFERENCES skill_definition (project_id, skill_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_points ADD CONSTRAINT fk_user_points_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE UNIQUE INDEX user_points_proj_skill_user_day ON user_points(project_id, skill_id, user_id, day);

CREATE TABLE user_achievement (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, project_id VARCHAR(255), skill_id VARCHAR(255), skill_ref_id INTEGER, level INTEGER, points_when_achieved INTEGER NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT user_achievement_pkey PRIMARY KEY (id));

CREATE INDEX index_user_achievement_user_id ON user_achievement(user_id);

CREATE INDEX index_user_achievement_skill_id ON user_achievement(skill_id);

CREATE INDEX index_user_achievement_skill_ref_id ON user_achievement(skill_ref_id);

CREATE INDEX index_user_achievement_project_id ON user_achievement(project_id);

ALTER TABLE user_achievement ADD CONSTRAINT fk_user_achievement_skill_ref_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_achievement ADD CONSTRAINT fk_user_achievement_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_achievement ADD CONSTRAINT fk_user_achievement_proj_id_skill_id FOREIGN KEY (project_id, skill_id) REFERENCES skill_definition (project_id, skill_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_achievement ADD CONSTRAINT fk_user_achievement_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE settings (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, setting VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, project_id VARCHAR(255), setting_group VARCHAR(255), user_ref_id INTEGER, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT settings_pkey PRIMARY KEY (id));

CREATE INDEX index_settings_project_id ON settings(project_id);

CREATE INDEX index_settings_setting_group ON settings(setting_group);

CREATE INDEX index_settings_setting ON settings(setting);

CREATE INDEX index_settings_user_id ON settings(user_ref_id);

CREATE INDEX index_settings_type ON settings(type);

ALTER TABLE settings ADD CONSTRAINT fk_settings_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE settings ADD CONSTRAINT fk_settings_user_id FOREIGN KEY (user_ref_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE global_badge_level_definition (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, proj_ref_id INTEGER NOT NULL, project_id VARCHAR(255) NOT NULL, project_name VARCHAR(255) NOT NULL, skill_id VARCHAR(255) NOT NULL, skill_ref_id INTEGER NOT NULL, level INTEGER NOT NULL, level_ref_id INTEGER NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT global_badge_level_definition_pkey PRIMARY KEY (id));

CREATE INDEX index_global_badge_level_definition_project_ref_id ON global_badge_level_definition(project_id);

CREATE INDEX index_global_badge_level_definition_skill_ref_id ON global_badge_level_definition(skill_id);

CREATE UNIQUE INDEX index_global_badge_level_definition_proj_skill_level ON global_badge_level_definition(proj_ref_id, skill_ref_id, level_ref_id);

ALTER TABLE global_badge_level_definition ADD CONSTRAINT fk_global_badge_level_definition_proj_ref_id FOREIGN KEY (proj_ref_id) REFERENCES project_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE global_badge_level_definition ADD CONSTRAINT fk_global_badge_level_skill_ref_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE global_badge_level_definition ADD CONSTRAINT fk_global_badge_level_level_ref_id FOREIGN KEY (level_ref_id) REFERENCES level_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::2::skills team
ALTER TABLE skill_definition ADD enabled VARCHAR(255) DEFAULT 'true';

ALTER TABLE user_achievement ADD notified VARCHAR(255) DEFAULT 'true';

UPDATE user_achievement SET notified = 'true';

CREATE TABLE password_reset_token (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INTEGER NOT NULL, token VARCHAR(255) NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, expires TIMESTAMP WITHOUT TIME ZONE NOT NULL, CONSTRAINT password_reset_token_pkey PRIMARY KEY (id));

CREATE UNIQUE INDEX index_password_reset_token_user_id ON password_reset_token(user_id);

CREATE UNIQUE INDEX index_password_reset_token_token ON password_reset_token(token);

ALTER TABLE password_reset_token ADD CONSTRAINT fk_password_reset_token_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE settings ALTER COLUMN value TYPE VARCHAR(3000) USING (value::VARCHAR(3000));

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::3::skills team
ALTER TABLE user_achievement ADD achieved_on TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

UPDATE user_achievement ua SET achieved_on=created where project_id is not null;

ALTER TABLE user_achievement ALTER COLUMN  achieved_on SET NOT NULL;

CREATE INDEX index_user_achievement_achieved_on ON user_achievement(achieved_on);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::4::skills team
CREATE TABLE user_events (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, project_id VARCHAR(255) NOT NULL, skill_ref_id INTEGER NOT NULL, event_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, event_type VARCHAR(255) NOT NULL, count INTEGER, week_number INTEGER, CONSTRAINT user_events_pkey PRIMARY KEY (id));

CREATE INDEX index_user_events_user_id ON user_events(user_id);

CREATE INDEX index_user_events_project_id ON user_events(project_id);

CREATE INDEX index_user_events_skill_ref_id ON user_events(skill_ref_id);

CREATE INDEX index_user_events_week_number ON user_events(week_number);

CREATE INDEX index_user_events_event_time ON user_events(event_time);

CREATE INDEX index_user_events_event_type ON user_events(event_type);

ALTER TABLE user_events ADD CONSTRAINT fk_user_events_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_events ADD CONSTRAINT fk_user_events_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_events ADD CONSTRAINT fk_user_events_skill_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_events ADD CONSTRAINT user_events_unique_row UNIQUE (user_id, project_id, skill_ref_id, event_time, event_type);

INSERT INTO skills_db_locks (lock) VALUES ('event_compaction_lock');

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::5::skills team
ALTER TABLE skill_definition ADD self_reporting_type VARCHAR(255);

CREATE TABLE skill_approval (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_id VARCHAR(255) NOT NULL, user_id VARCHAR(255) NOT NULL, skill_ref_id INTEGER NOT NULL, requested_on TIMESTAMP WITHOUT TIME ZONE NOT NULL, rejected_on TIMESTAMP WITHOUT TIME ZONE, request_msg TEXT, rejection_msg TEXT, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT skill_approval_pkey PRIMARY KEY (id));

CREATE INDEX index_skill_approval_user_id ON skill_approval(user_id);

CREATE INDEX index_skill_approval_project_id ON skill_approval(project_id);

CREATE INDEX index_skill_approval_skill_ref_id ON skill_approval(skill_ref_id);

CREATE INDEX index_skill_approval_rejected_on ON skill_approval(rejected_on);

ALTER TABLE skill_approval ADD CONSTRAINT fk_skill_approval_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE skill_approval ADD CONSTRAINT fk_skill_approval_skill_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE skill_approval ADD CONSTRAINT fk_skill_approval_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE skill_approval ADD CONSTRAINT skill_approval_unique_row UNIQUE (user_id, skill_ref_id);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::6::skills team
CREATE TABLE project_error (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_id VARCHAR(255) NOT NULL, error_type VARCHAR(255) NOT NULL, error VARCHAR(255) NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, last_seen TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, count INTEGER, CONSTRAINT project_error_pkey PRIMARY KEY (id));

ALTER TABLE project_error ADD CONSTRAINT fk_project_error_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX index_project_error_project_id ON project_error(project_id);

CREATE INDEX index_project_error_error ON project_error(error);

CREATE INDEX index_project_error_project_id_error_type ON project_error(error_type, project_id);

CREATE INDEX index_project_error_project_id_error_type_error ON project_error(error_type, project_id, error);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::7::skills team
CREATE TABLE notifications (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, requested_on TIMESTAMP WITHOUT TIME ZONE NOT NULL, type TEXT NOT NULL, encoded_params TEXT NOT NULL, failed_count INTEGER NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT notifications_pkey PRIMARY KEY (id));

CREATE INDEX notifications_user_id ON notifications(user_id);

CREATE INDEX notifications_requested_on ON notifications(requested_on);

CREATE INDEX notifications_retry_count ON notifications(failed_count);

ALTER TABLE notifications ADD CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

INSERT INTO skills_db_locks (lock) VALUES ('notifier_lock');

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::8::skills team
ALTER TABLE settings ALTER COLUMN value TYPE TEXT USING (value::TEXT);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::9::skills team
delete from settings where setting_group = 'pinned_project' and user_ref_id in (select distinct user_ref_id from user_roles where role_name = 'ROLE_SUPER_DUPER_USER');

delete from settings where setting_group = 'project_sort_order' and user_ref_id in (select distinct user_ref_id from user_roles where role_name = 'ROLE_SUPER_DUPER_USER');

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::10::skills team
INSERT INTO skills_db_locks (lock) VALUES ('project_expiration_lock');

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::11::skills team
ALTER TABLE notifications DROP CONSTRAINT fk_notifications_user_id;

DROP INDEX notifications_user_id;

ALTER TABLE notifications ALTER COLUMN user_id TYPE TEXT USING (user_id::TEXT);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::12::skills team
CREATE TABLE user_tags (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, key VARCHAR(255), value VARCHAR(255), created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT user_tags_pkey PRIMARY KEY (id));

CREATE INDEX index_users_tags_user_id ON user_tags(user_id);

ALTER TABLE user_tags ADD CONSTRAINT fk_user_tags_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_attrs ADD user_tags_last_updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL;

INSERT INTO skills_db_locks (lock) VALUES ('create_or_update_user');

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::13::skills team
ALTER TABLE skill_approval DROP CONSTRAINT skill_approval_unique_row;

ALTER TABLE skill_approval ADD approver_action_taken_on TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE skill_approval ADD rejection_acknowledged_on TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE skill_approval ADD approver_user_id VARCHAR(255);

CREATE INDEX index_skill_approval_approver_action_taken_on ON skill_approval(approver_action_taken_on);

CREATE INDEX "index_skill_approval_approver_user_id " ON skill_approval(approver_user_id);

update skill_approval set approver_action_taken_on = rejected_on where rejected_on is not null;

update skill_approval ap set approver_user_id = (select user_id from user_roles ur where ur.project_id = ap.project_id and ur.role_name = 'ROLE_PROJECT_ADMIN' limit 1) where rejected_on is not null;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::14::skills team
CREATE INDEX index_users_tags_key ON user_tags(key);

CREATE INDEX index_users_tags_value ON user_tags(value);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::15::skills team
ALTER TABLE skill_definition ADD num_skills_required INTEGER DEFAULT 0 NOT NULL;

ALTER TABLE skill_definition ADD group_id VARCHAR(255);

ALTER TABLE user_points ADD contributes_to_skills_group VARCHAR(255);

CREATE INDEX index_user_points_contributes_to_skills_group ON user_points(contributes_to_skills_group);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::16::skills team
update skill_definition set enabled = 'true' where enabled is null;

ALTER TABLE skill_definition ALTER COLUMN  enabled SET NOT NULL;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::17::skills team
update skill_definition set enabled = 'true' where enabled = 'false' and type = 'Skill' and group_id is null;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::18::skills team
ALTER TABLE password_reset_token RENAME TO user_token;

ALTER TABLE user_token ADD type VARCHAR(255) NOT NULL;

ALTER TABLE user_attrs ADD email_verified VARCHAR(255) DEFAULT 'false';

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::19::skills team
ALTER TABLE user_token DROP CONSTRAINT fk_password_reset_token_user_id;

DROP INDEX index_password_reset_token_user_id;

ALTER TABLE user_token ADD CONSTRAINT fk_password_reset_token_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::20::skills team
update skill_definition childSkill SET group_id = groupSkill.skill_id
            from skill_definition groupSkill, skill_relationship_definition rel
            where groupSkill.id = rel.parent_ref_id
              and rel.child_ref_id = childSkill.id
              and rel.type='SkillsGroupRequirement'
              and childSkill.group_id is not null
              and groupSkill.skill_id <> childSkill.group_id;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::21::skills team
ALTER TABLE skill_definition ADD read_only VARCHAR(255) DEFAULT 'false' NOT NULL;

ALTER TABLE skill_definition ADD copied_from_skill_ref INTEGER;

ALTER TABLE skill_definition ADD copied_from_project_id VARCHAR(255);

ALTER TABLE skill_definition ADD CONSTRAINT fk_original_skill_skill_id FOREIGN KEY (copied_from_skill_ref) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE skill_definition ADD CONSTRAINT fk_skill_definition_project_definition_copy_from_project_id FOREIGN KEY (copied_from_project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX index_skill_definition_copied_from_project_id ON skill_definition(copied_from_project_id);

CREATE TABLE exported_skills (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, skill_ref_id INTEGER NOT NULL, exported_from_project_id VARCHAR(255) NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT exported_skills_pkey PRIMARY KEY (id));

CREATE TABLE skill_updated_queue (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, skill_ref_id INTEGER NOT NULL, is_catalog_skill VARCHAR(255) DEFAULT 'false' NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT skill_updated_queue_pkey PRIMARY KEY (id));

ALTER TABLE exported_skills ADD CONSTRAINT fk_exported_skills_skill_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE exported_skills ADD CONSTRAINT fk_exported_skills_project_id FOREIGN KEY (exported_from_project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE skill_updated_queue ADD CONSTRAINT fk_skill_updated_queue_skill_ref_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX index_exported_skills_exported_from_project_id ON exported_skills(exported_from_project_id);

CREATE INDEX index_exported_skills_skill_ref_id ON exported_skills(skill_ref_id);

INSERT INTO skills_db_locks (lock) VALUES ('catalog_skill_update_lock');

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::22::skills team
CREATE TABLE scheduled_tasks (task_name TEXT NOT NULL, task_instance TEXT NOT NULL, task_data BYTEA, execution_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, picked BOOLEAN NOT NULL, picked_by TEXT, last_success TIMESTAMP WITHOUT TIME ZONE, last_failure TIMESTAMP WITHOUT TIME ZONE, consecutive_failures INTEGER, last_heartbeat TIMESTAMP WITHOUT TIME ZONE, version BIGINT);

ALTER TABLE scheduled_tasks ADD PRIMARY KEY (task_name, task_instance);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::23::skills team
create index index_user_performed_skill_skill_id_like on user_performed_skill (lower(skill_id) varchar_pattern_ops);

create index index_user_performed_skill_skill_id_lower on user_performed_skill (lower(skill_id));

create index index_user_events_project_id_lower on user_events (lower(project_id));

create index index_skill_definition_project_id_lower on skill_definition (lower(project_id));

create index index_settings_project_id_lower on settings (lower(project_id));

create index index_project_definition_name_like on project_definition (lower(name) varchar_pattern_ops);

create index index_project_definition_name_lower on project_definition (lower(name));

create index index_user_performed_skill_user_id_like on user_performed_skill (lower(user_id) varchar_pattern_ops);

create index index_user_performed_skill_user_id_lower on user_performed_skill (lower(user_id));

create index index_user_tags_value_like on user_tags (lower(value) varchar_pattern_ops);

create index index_user_tags_value_lower on user_tags (lower(value));

create index index_user_attrs_user_id_for_display_like on user_attrs (lower(user_id_for_display) varchar_pattern_ops);

create index index_user_attrs_user_id_for_display_lower on user_attrs (lower(user_id_for_display));

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::24::skills team
ALTER TABLE skills_db_locks ADD expires VARCHAR(255) DEFAULT 'false' NOT NULL;

UPDATE skills_db_locks SET expires = 'false';

CREATE FUNCTION f_select_lock_and_insert(
                _lockKey varchar,
                OUT id integer,
                OUT lock character varying(255),
                OUT created timestamp without time zone,
                OUT updated timestamp without time zone,
                OUT expires character varying(255)
            )
            AS $func$
            #variable_conflict use_column
            BEGIN
            LOOP
                SELECT sdl.id, sdl.lock, sdl.created, sdl.updated, sdl.expires
                FROM   skills_db_locks sdl
                WHERE  sdl.lock = _lockKey
                FOR UPDATE
                INTO id, lock, created, updated, expires;

                EXIT WHEN FOUND;

                INSERT INTO skills_db_locks AS l (lock, expires)
                VALUES (_lockKey, 'true')
                ON CONFLICT (lock) DO NOTHING
                RETURNING l.id, l.lock, l.created, l.updated, l.expires
                INTO id, lock, created, updated, expires;

                EXIT WHEN FOUND;
            END LOOP;
            END;
            $func$
            LANGUAGE plpgsql;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::25::skills team
delete from user_points where day is not null;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::26::skills team
DROP INDEX user_points_proj_skill_user_day;

DROP INDEX index_user_points_day;

ALTER TABLE user_points DROP COLUMN day;

CREATE UNIQUE INDEX user_points_proj_skill_user ON user_points(project_id, skill_id, user_id);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::27::skills team
delete from user_points up
            using skill_definition sd
            where up.project_id = sd.project_id and
                up.skill_id = sd.skill_id and
                sd.type = 'SkillsGroup';

update skill_definition sd
            set enabled = 'true'
            where ((sd.type = 'Skill' and sd.group_id is not null) OR sd.type = 'SkillsGroup') and sd.enabled = 'false';

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::28::skills team
CREATE TABLE project_access_token (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, proj_ref_id INTEGER NOT NULL, token VARCHAR(255) NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, expires TIMESTAMP WITHOUT TIME ZONE NOT NULL, claimed TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT project_access_token_pkey PRIMARY KEY (id));

CREATE UNIQUE INDEX index_project_access_token_token ON project_access_token(token);

ALTER TABLE project_access_token ADD CONSTRAINT fk_project_access_token_proj_ref_id_project_definition_id FOREIGN KEY (proj_ref_id) REFERENCES project_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::29::skills team
ALTER TABLE skill_definition ADD justification_required VARCHAR(255) DEFAULT 'false';

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::30::skills team
ALTER TABLE project_access_token ADD recipient_email VARCHAR(255);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::31::skills team
ALTER TABLE project_definition ADD description TEXT;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::32::skills team
CREATE TABLE client_preferences (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, project_id VARCHAR(255), user_id VARCHAR(255), created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT client_preferences_pkey PRIMARY KEY (id));

CREATE INDEX index_client_preferences_project_id ON client_preferences(project_id);

CREATE INDEX index_client_preferences_key ON client_preferences(key);

CREATE INDEX index_client_preferences_user_id ON client_preferences(user_id);

ALTER TABLE client_preferences ADD CONSTRAINT fk_client_preferences_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::33::skills team
update skill_definition child
            set group_id = parent.skill_id
            from skill_relationship_definition rel,
                 skill_definition parent
            where parent.id = rel.parent_ref_id
              and child.id = rel.child_ref_id
              and parent.type = 'SkillsGroup'
              and rel.type = 'SkillsGroupRequirement'
              and (parent.skill_id != child.group_id or child.group_id is null);

update skill_definition child
            set group_id = null
            from skill_relationship_definition rel,
                 skill_definition parent
            where parent.id = rel.parent_ref_id
              and child.id = rel.child_ref_id
              and parent.type = 'Subject'
              and rel.type = 'RuleSetDefinition'
              and (child.group_id is not null);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::34::skills team
CREATE INDEX index_project_access_token_recipient ON project_access_token(recipient_email);

CREATE UNIQUE INDEX index_project_access_token_recipient_project_id ON project_access_token(recipient_email, proj_ref_id);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::35::skills team
CREATE TABLE skill_approval_conf (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_id VARCHAR(255) NOT NULL, approver_user_id VARCHAR(255) NOT NULL, user_id VARCHAR(255), skill_ref_id INTEGER, user_tag_key VARCHAR(255), user_tag_value VARCHAR(255), created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT skill_approval_conf_pkey PRIMARY KEY (id));

CREATE INDEX index_skill_approval_conf_project_id ON skill_approval_conf(project_id);

CREATE INDEX index_skill_approval_conf_approver_user_id ON skill_approval_conf(approver_user_id);

CREATE INDEX index_skill_approval_conf_user_id ON skill_approval_conf(user_id);

CREATE INDEX index_skill_approval_conf_skill_ref_id ON skill_approval_conf(skill_ref_id);

CREATE INDEX index_skill_approval_conf_user_tag_key ON skill_approval_conf(user_tag_key);

CREATE INDEX index_skill_approval_conf_user_tag_value ON skill_approval_conf(user_tag_value);

ALTER TABLE skill_approval_conf ADD CONSTRAINT fk_skill_approval_conf_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE skill_approval_conf ADD CONSTRAINT fk_skill_approval_conf_approver_user_id FOREIGN KEY (approver_user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE skill_approval_conf ADD CONSTRAINT fk_skill_approval_conf_skill_ref_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE skill_approval_conf ADD CONSTRAINT fk_skill_approval_conf_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::36::skills team
CREATE TABLE attachments (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(255) NOT NULL, filename VARCHAR(255), content OID, content_type VARCHAR(255), size BIGINT, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT attachments_pkey PRIMARY KEY (id));

CREATE INDEX index_attachments_filename ON attachments(filename);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::37::skills team
CREATE TABLE quiz_definition (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, quiz_id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, description TEXT, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT quiz_definition_pkey PRIMARY KEY (id));

CREATE UNIQUE INDEX index_quiz_definition_quiz_id ON quiz_definition(quiz_id);

CREATE UNIQUE INDEX index_quiz_definition_name ON quiz_definition(name);

ALTER TABLE user_roles ADD quiz_id VARCHAR(255);

ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_quiz_id FOREIGN KEY (quiz_id) REFERENCES quiz_definition (quiz_id) ON UPDATE CASCADE ON DELETE CASCADE;

INSERT INTO skills_db_locks (lock) VALUES ('quizDefs_lock');

CREATE TABLE quiz_question_definition (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, quiz_id VARCHAR(255) NOT NULL, question TEXT NOT NULL, type VARCHAR(255) NOT NULL, display_order INTEGER NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT quiz_question_definition_pkey PRIMARY KEY (id));

CREATE INDEX fk_quiz_question_definition_quiz_id ON quiz_question_definition(quiz_id);

ALTER TABLE quiz_question_definition ADD CONSTRAINT fk_quiz_question_definition_quiz_id FOREIGN KEY (quiz_id) REFERENCES quiz_definition (quiz_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE quiz_answer_definition (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, quiz_id VARCHAR(255) NOT NULL, question_ref_id INTEGER NOT NULL, answer TEXT, is_correct_answer VARCHAR(255) NOT NULL, display_order INTEGER NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT quiz_answer_definition_pkey PRIMARY KEY (id));

CREATE INDEX fk_quiz_answer_definition_question_ref_id ON quiz_answer_definition(question_ref_id);

ALTER TABLE quiz_answer_definition ADD CONSTRAINT fk_quiz_answer_definition_question_ref_id FOREIGN KEY (question_ref_id) REFERENCES quiz_question_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX fk_quiz_answer_definition_quiz_id ON quiz_answer_definition(quiz_id);

ALTER TABLE quiz_answer_definition ADD CONSTRAINT fk_quiz_answer_definition_quiz_id FOREIGN KEY (quiz_id) REFERENCES quiz_definition (quiz_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE user_quiz_attempt (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, quiz_definition_ref_id INTEGER NOT NULL, status VARCHAR(255) NOT NULL, user_id VARCHAR(255) NOT NULL, started TIMESTAMP WITHOUT TIME ZONE NOT NULL, completed TIMESTAMP WITHOUT TIME ZONE, num_questions_to_pass INTEGER NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT user_quiz_attempt_pkey PRIMARY KEY (id));

CREATE INDEX user_quiz_attempt_status ON user_quiz_attempt(status);

CREATE INDEX fk_user_quiz_attempt_quiz_definition_ref_id ON user_quiz_attempt(quiz_definition_ref_id);

ALTER TABLE user_quiz_attempt ADD CONSTRAINT fk_quiz_user_quiz_attempt_quiz_definition_ref_id FOREIGN KEY (quiz_definition_ref_id) REFERENCES quiz_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX fk_user_quiz_attempt_user_id ON user_quiz_attempt(user_id);

ALTER TABLE user_quiz_attempt ADD CONSTRAINT fk_user_quiz_attempt_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE user_quiz_question_attempt (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_quiz_attempt_ref_id INTEGER NOT NULL, quiz_question_definition_ref_id INTEGER NOT NULL, status VARCHAR(255) NOT NULL, user_id VARCHAR(255) NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT user_quiz_question_attempt_pkey PRIMARY KEY (id));

CREATE INDEX user_quiz_question_attempt_status ON user_quiz_question_attempt(status);

CREATE INDEX fk_user_quiz_question_attempt_user_quiz_attempt_ref_id ON user_quiz_question_attempt(user_quiz_attempt_ref_id);

ALTER TABLE user_quiz_question_attempt ADD CONSTRAINT fk_user_quiz_question_attempt_user_quiz_attempt_ref_id FOREIGN KEY (user_quiz_attempt_ref_id) REFERENCES user_quiz_attempt (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX fk_user_quiz_question_attempt_quiz_question_definition_ref_id ON user_quiz_question_attempt(quiz_question_definition_ref_id);

ALTER TABLE user_quiz_question_attempt ADD CONSTRAINT fk_user_quiz_question_attempt_quiz_question_definition_ref_id FOREIGN KEY (quiz_question_definition_ref_id) REFERENCES quiz_question_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX fk_user_quiz_question_attempt_user_id ON user_quiz_question_attempt(user_id);

ALTER TABLE user_quiz_question_attempt ADD CONSTRAINT fk_user_quiz_question_attempt_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE user_quiz_answer_attempt (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_quiz_attempt_ref_id INTEGER NOT NULL, quiz_answer_definition_ref_id INTEGER NOT NULL, answer TEXT, user_id VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT user_quiz_answer_attempt_pkey PRIMARY KEY (id));

CREATE INDEX user_quiz_answer_attempt_status ON user_quiz_answer_attempt(status);

CREATE INDEX fk_user_quiz_answer_attempt_user_quiz_attempt_ref_i ON user_quiz_answer_attempt(user_quiz_attempt_ref_id);

ALTER TABLE user_quiz_answer_attempt ADD CONSTRAINT fk_user_quiz_answer_attempt_user_quiz_attempt_ref_id FOREIGN KEY (user_quiz_attempt_ref_id) REFERENCES user_quiz_attempt (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX fk_user_quiz_answer_attempt_user_quiz_answer_definition_ref_id ON user_quiz_answer_attempt(quiz_answer_definition_ref_id);

ALTER TABLE user_quiz_answer_attempt ADD CONSTRAINT fk_user_quiz_answer_attempt_quiz_answer_definition_ref_id FOREIGN KEY (quiz_answer_definition_ref_id) REFERENCES quiz_answer_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX fk_user_quiz_answer_attempt_user_id ON user_quiz_answer_attempt(user_id);

ALTER TABLE user_quiz_answer_attempt ADD CONSTRAINT fk_user_quiz_answer_attempt_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE quiz_to_skill_definition (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, quiz_ref_id INTEGER NOT NULL, skill_ref_id INTEGER NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT quiz_to_skill_definition_pkey PRIMARY KEY (id));

CREATE INDEX fk_quiz_to_skill_definition_quiz_ref_id ON quiz_to_skill_definition(quiz_ref_id);

ALTER TABLE quiz_to_skill_definition ADD CONSTRAINT fk_quiz_to_skill_definition_quiz_ref_id FOREIGN KEY (quiz_ref_id) REFERENCES quiz_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE UNIQUE INDEX fk_quiz_to_skill_definition_skill_ref_id ON quiz_to_skill_definition(skill_ref_id);

ALTER TABLE quiz_to_skill_definition ADD CONSTRAINT fk_quiz_to_skill_definition_skill_ref_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE quiz_settings (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, setting VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, quiz_ref_id INTEGER, user_ref_id INTEGER, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT quiz_settings_pkey PRIMARY KEY (id));

CREATE INDEX index_quiz_settings_setting ON quiz_settings(setting);

CREATE INDEX fk_quiz_settings_quiz_ref_id ON quiz_settings(quiz_ref_id);

ALTER TABLE quiz_settings ADD CONSTRAINT fk_quiz_settings_quiz_ref_id FOREIGN KEY (quiz_ref_id) REFERENCES quiz_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE quiz_settings ADD CONSTRAINT fk_quiz_settings_user_ref_id FOREIGN KEY (user_ref_id) REFERENCES user_attrs (id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::38::skills team
ALTER TABLE attachments ADD user_id VARCHAR(255);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::39::skills team
UPDATE level_definition l
            SET points_from=null,
                points_to=null
                from project_definition p,
             settings settings
                    where p.id = l.project_ref_id
                      and l.skill_ref_id is null
                      and p.project_id != 'Inception'
          and p.project_id = settings.project_id
          and settings.setting = 'level.points.enabled'
          and settings.value = 'false';

UPDATE level_definition l
        SET points_from=null,
            points_to=null
            from skill_definition s,
             settings settings
                where s.id = l.skill_ref_id
                  and s.project_id != 'Inception'
          and s.project_id = settings.project_id
          and settings.setting = 'level.points.enabled'
          and settings.value = 'false';

delete
        from project_error
        where id in (
            select error.id
            from project_error error, settings settings
            where error.error_type in ('UnachievableProjectLevel', 'UnachievableSubjectLevel')
              and error.project_id = settings.project_id
              and settings.setting = 'level.points.enabled'
              and settings.value = 'false'
        );

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::40::skills team
CREATE TABLE skill_attributes_definition (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, skill_ref_id INTEGER NOT NULL, type VARCHAR(255) NOT NULL, attributes JSONB NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT skill_attributes_definition_pkey PRIMARY KEY (id));

CREATE INDEX index_skill_attributes_definition_skill_ref_id ON skill_attributes_definition(skill_ref_id);

CREATE INDEX index_skill_attributes_definition_type ON skill_attributes_definition(type);

ALTER TABLE skill_attributes_definition ADD CONSTRAINT fk_skill_attributes_definition_skill_ref_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::41::skills team
ALTER TABLE attachments ADD project_id VARCHAR(255);

ALTER TABLE attachments ADD quiz_id VARCHAR(255);

ALTER TABLE attachments ADD skill_id VARCHAR(255);

CREATE INDEX index_attachments_project_id ON attachments(project_id);

CREATE INDEX index_attachments_quiz_id ON attachments(quiz_id);

CREATE INDEX index_attachments_skill_id ON attachments(skill_id);

ALTER TABLE attachments ADD CONSTRAINT fk_attachments_project_definition_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE attachments ADD CONSTRAINT fk_attachments_quiz_id FOREIGN KEY (quiz_id) REFERENCES quiz_definition (quiz_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE attachments ADD CONSTRAINT fk_attachments_proj_id_skill_id FOREIGN KEY (project_id, skill_id) REFERENCES skill_definition (project_id, skill_id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::42::skills team
ALTER TABLE user_quiz_question_attempt ADD display_order INTEGER;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::43::skills team
CREATE TABLE expired_user_achievement (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, project_id VARCHAR(255), skill_id VARCHAR(255), skill_ref_id INTEGER, level INTEGER, points_when_achieved INTEGER NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, notified VARCHAR(255) DEFAULT 'true', achieved_on TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), expired_on TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT expired_user_achievement_pkey PRIMARY KEY (id));

ALTER TABLE expired_user_achievement ADD CONSTRAINT fk_expired_user_achievement_skill_ref_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE expired_user_achievement ADD CONSTRAINT fk_expired_user_achievement_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE expired_user_achievement ADD CONSTRAINT fk_expired_user_achievement_proj_id_skill_id FOREIGN KEY (project_id, skill_id) REFERENCES skill_definition (project_id, skill_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE expired_user_achievement ADD CONSTRAINT fk_expired_user_achievement_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::44::skills team
CREATE TABLE user_actions_history (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, item VARCHAR(255) NOT NULL, item_id VARCHAR(255) NOT NULL, item_ref_id INTEGER, user_id VARCHAR(255) NOT NULL, project_id VARCHAR(255), quiz_id VARCHAR(255), action_attributes JSONB, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT user_actions_history_pkey PRIMARY KEY (id));

CREATE INDEX index_user_actions_history_action ON user_actions_history(action);

CREATE INDEX index_user_actions_history_item ON user_actions_history(item);

CREATE INDEX index_user_actions_history_item_id ON user_actions_history(item_id);

CREATE INDEX index_user_actions_history_item_ref_id ON user_actions_history(item_ref_id);

CREATE INDEX index_user_actions_history_user_id ON user_actions_history(user_id);

ALTER TABLE user_actions_history ADD CONSTRAINT fk_user_actions_history_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX index_user_actions_history_project_id ON user_actions_history(project_id);

CREATE INDEX index_user_actions_history_quiz_id ON user_actions_history(quiz_id);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::45::skills team
delete from user_actions_history where item = 'SkillEvents' and action = 'Create';

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::46::skills team
INSERT INTO skills_db_locks (lock) VALUES ('upgrade_replay_skill_events');

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::47::skills team
CREATE TABLE user_quiz_answer_graded (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_quiz_answer_attempt_ref_id INTEGER NOT NULL, grader_user_attrs_ref_id INTEGER NOT NULL, feedback TEXT, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT user_quiz_answer_graded_pkey PRIMARY KEY (id));

CREATE UNIQUE INDEX index_user_quiz_answer_graded_user_quiz_answer_attempt_ref_id ON user_quiz_answer_graded(user_quiz_answer_attempt_ref_id);

ALTER TABLE user_quiz_answer_graded ADD CONSTRAINT fk_user_quiz_answer_graded_user_quiz_answer_attempt_ref_id FOREIGN KEY (user_quiz_answer_attempt_ref_id) REFERENCES user_quiz_answer_attempt (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX index_user_quiz_answer_graded_grader_user_attrs_ref_id ON user_quiz_answer_graded(grader_user_attrs_ref_id);

ALTER TABLE user_quiz_answer_graded ADD CONSTRAINT fk_user_quiz_answer_graded_grader_user_attrs_ref_id FOREIGN KEY (grader_user_attrs_ref_id) REFERENCES user_attrs (id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::48::skills team
CREATE TABLE admin_group_definition (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, admin_group_id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, protected_community_enabled VARCHAR(255) DEFAULT 'false' NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT admin_group_definition_pkey PRIMARY KEY (id));

INSERT INTO skills_db_locks (lock) VALUES ('adminGroupDefs_lock');

CREATE UNIQUE INDEX index_admin_group_definition_admin_group_id ON admin_group_definition(admin_group_id);

CREATE UNIQUE INDEX index_admin_group_definition_name ON admin_group_definition(name);

ALTER TABLE user_roles ADD admin_group_id VARCHAR(255);

ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_admin_group_id FOREIGN KEY (admin_group_id) REFERENCES admin_group_definition (admin_group_id) ON UPDATE CASCADE ON DELETE CASCADE;

DROP INDEX index_user_roles_user_id_role_name_project_id;

CREATE UNIQUE INDEX index_user_roles_user_id_role_name_project_id_quiz_id_admin_group_id ON user_roles(user_id, role_name, project_id, quiz_id, admin_group_id);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::49::skills team
CREATE TABLE archived_users (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, project_id VARCHAR(255) NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT archived_users_pkey PRIMARY KEY (id));

CREATE INDEX index_archived_users_project_id ON archived_users(project_id);

CREATE UNIQUE INDEX index_archived_users_project_id_user_id ON archived_users(user_id, project_id);

ALTER TABLE archived_users ADD CONSTRAINT fk_archived_users_project_id FOREIGN KEY (project_id) REFERENCES project_definition (project_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE archived_users ADD CONSTRAINT fk_archived_users_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::50::skills team
ALTER TABLE quiz_question_definition ADD answer_hint TEXT;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::51::skills team
ALTER TABLE quiz_question_definition ADD attributes JSONB;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::52::skills team
CREATE TABLE web_notifications (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, lookup_id VARCHAR(255), user_id VARCHAR(255), title VARCHAR(255), notification TEXT, notified_on TIMESTAMP WITHOUT TIME ZONE NOT NULL, show_until TIMESTAMP WITHOUT TIME ZONE, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT web_notifications_pkey PRIMARY KEY (id));

CREATE INDEX index_lookup_id_user_id ON web_notifications(lookup_id);

CREATE INDEX index_web_notifications_user_id ON web_notifications(user_id);

CREATE INDEX index_web_notifications_notified_on ON web_notifications(notified_on);

CREATE INDEX index_web_notifications_show_until ON web_notifications(show_until);

ALTER TABLE web_notifications ADD CONSTRAINT fk_web_notifications_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE web_notifications_ack (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, web_notifications_ref_id INTEGER NOT NULL, created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, updated TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT web_notifications_ack_pkey PRIMARY KEY (id));

CREATE INDEX index_web_notifications_ack_user_id ON web_notifications_ack(user_id);

ALTER TABLE web_notifications_ack ADD CONSTRAINT fk_web_notifications_ack_user_id FOREIGN KEY (user_id) REFERENCES user_attrs (user_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX index_web_notifications_ack_notification_ref_id ON web_notifications_ack(web_notifications_ref_id);

ALTER TABLE web_notifications_ack ADD CONSTRAINT fk_web_notifications_ack_notification_ref_id FOREIGN KEY (web_notifications_ref_id) REFERENCES web_notifications (id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::53::skills team
ALTER TABLE user_roles ADD global_badge_id VARCHAR(255);

DROP INDEX index_user_roles_user_id_role_name_project_id_quiz_id_admin_group_id;

CREATE UNIQUE INDEX index_user_roles_user_id_role_name_project_id_quiz_id_admin_group_id_global_badge_id ON user_roles(user_id, role_name, project_id, quiz_id, admin_group_id, global_badge_id);

ALTER TABLE custom_icons ADD global_badge_id VARCHAR(255);

CREATE INDEX index_custom_icons_global_badge_id ON custom_icons(global_badge_id);

CREATE UNIQUE INDEX index_custom_icons_global_badge_id_filename ON custom_icons(global_badge_id, filename);

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::54::skills team
WITH supervisor_users AS (
                SELECT DISTINCT user_id, user_ref_id
                FROM user_roles
                WHERE role_name = 'ROLE_SUPERVISOR'
                  AND project_id IS NULL
                  AND quiz_id IS NULL
                  AND admin_group_id IS NULL
            ),
                 global_badges AS (
                     SELECT skill_id
                     FROM skill_definition
                     WHERE type = 'GlobalBadge'
                 )
            INSERT INTO user_roles (user_id, user_ref_id, role_name, global_badge_id)
            SELECT su.user_id, su.user_ref_id, 'ROLE_GLOBAL_BADGE_ADMIN' as role_name, gb.skill_id
            FROM
                supervisor_users su
                    CROSS JOIN
                global_badges gb;

DELETE FROM user_roles WHERE role_name = 'ROLE_SUPERVISOR' AND project_id IS NULL AND quiz_id IS NULL AND admin_group_id IS NULL AND global_badge_id IS NULL;

WITH global_custom_icons AS (
                SELECT filename, max(content_type) as content_type, max(data_uri) as data_uri, max(width) as width, max(height) as height
                FROM custom_icons
                WHERE project_id IS NULL
                AND global_badge_id IS NULL
                group by filename
            ),
                 global_badges AS (
                     SELECT skill_id
                     FROM skill_definition
                     WHERE type = 'GlobalBadge'
                 )
            INSERT INTO custom_icons (filename, content_type, data_uri, width, height, global_badge_id)
            SELECT gci.filename, gci.content_type, gci.data_uri, gci.width, gci.height, gb.skill_id
            FROM
                global_custom_icons gci
                    CROSS JOIN
                global_badges gb;

UPDATE skill_definition
            SET icon_class = CONCAT(skill_id, SUBSTRING(icon_class, 7))
            WHERE type = 'GlobalBadge'
              AND icon_class LIKE 'GLOBAL-%';

DELETE FROM custom_icons WHERE project_id IS NULL AND global_badge_id IS NULL;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::55::skills team
ALTER TABLE quiz_definition ADD attributes JSONB;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::56::skills team
ALTER TABLE settings ADD skill_ref_id INTEGER;

CREATE INDEX index_settings_skill_ref_id ON settings(skill_ref_id);

ALTER TABLE settings ADD CONSTRAINT fk_settings_skill_ref_id FOREIGN KEY (skill_ref_id) REFERENCES skill_definition (id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::57::skills team
ALTER TABLE quiz_answer_definition ADD multi_part_answer JSONB;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::58::skills team
UPDATE quiz_question_definition
            SET attributes = jsonb_build_object('videoConf', attributes)
            WHERE attributes IS NOT NULL
              AND attributes ->>'videoConf' IS NULL;

INSERT INTO user_attrs (user_id, user_id_for_display, first_name, last_name, created, updated)
            VALUES ('ai-grader', 'AI Assistant', 'AI', 'Grader', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

ALTER TABLE user_quiz_answer_graded ADD ai_confidence_level INTEGER;

ALTER TABLE user_quiz_answer_attempt ADD ai_grading_attempt_count INTEGER DEFAULT 0;

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::59::skills team
ALTER TABLE user_achievement ADD expiration_notification_state VARCHAR(50) DEFAULT 'NONE';

ALTER TABLE expired_user_achievement ADD expiration_notification_state VARCHAR(50) DEFAULT 'NONE';

INSERT INTO skills_db_locks (lock) VALUES ('skill_expiration_lock');

-- Changeset src/main/resources/db/changelog/db.changelog-master.xml::60::skills team
UPDATE user_attrs SET first_name = '' WHERE first_name LIKE '%<%';

UPDATE user_attrs SET last_name = '' WHERE last_name LIKE '%<%';

UPDATE user_attrs SET nickname = '' WHERE nickname LIKE '%<%';

