org.ocpsoft.prettytime--prettytime--5.0.3.Final=The Apache Software License, Version 2.0
org.springframework.session--spring-session-core--4.1.1=The Apache Software License, Version 2.0
org.springframework.session--spring-session-jdbc--4.1.1=The Apache Software License, Version 2.0
